name: Sedstart Prod
 
on:
  workflow_dispatch:
 
jobs:
  sedstart-run:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger SedStart test run
        uses: sedinqa/sedstart@v1
        with:
          api_key: ${{ secrets.SEDSTART_API_KEY_PROD }}
          project_id: 535
          test_id: 4649
          profile_id: 883
          browser: 
          headless: false
