name: Sedstart Prod
 
on:
  workflow_dispatch:
jobs:
  sedstart-run:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger SedStart test run
        uses: sedinqa/sedstart@v1
        with:
          api_key: ${{ secrets.SEDSTART_API_KEY_PROD }}
          project_id: 1296
          test_id: 1085
          profile_id: 2307
          browser: chrome
          headless: false
